### PR TITLE
Translations on the main page

### PR DESCRIPTION
**Pull request by khrizzcristian**
I added in translation two texts from the main page.

- Main page title
- "Show only differences" button

Screenshot here

[Workspace here](https://longo--biasicom.myvtex.com/product-comparison)

### CODE REVIEW

**Comment by khrizzcristian** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [X]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by santosluiz000** [comment]
@khrizzcristian there conflicts in your branch. Please, check it

**Comment by khrizzcristian** [comment]
> @khrizzcristian there conflicts on your branch. Please, check it

Fixed :)

**Review by santosluiz000 — APPROVED** [review]

**Comment by alexdinca** [comment]
@santosluiz000 can we merge this please?

**Comment by khrizzcristian** [comment]
Can we merge this please?

**Review by gsasouza — APPROVED** [review]

**Pull request merged**
